<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::truncate();

        $products = [
            // Staples & Buy It Again
            [
                'slug' => 'atta',
                'name' => 'Chakki Atta',
                'subtitle_tag' => '100% STONE GROUND WHOLE WHEAT',
                'category' => 'staples',
                'category_title' => 'Staples · Flour',
                'price' => 18.99,
                'original_price' => 18.99,
                'unit_price' => '$0.95 / lb',
                'stock_badge' => 'Staple · buy monthly',
                'photo_label' => 'atta bag',
                'image' => '/images/products/atta.jpg',
                'size_main' => '20 lb',
                'size_sub' => '9.07 kg · ~80 rotis',
                'freshness_line' => 'Freshly milled batch · Zero maida added',
                'description' => 'Traditional chakki stone-ground whole wheat flour for ultra-soft, fluffy phulkas and rotis.',
                'servings' => null,
                'cooking_time' => null,
                'is_recipe_kit' => false,
                'buy_again' => true,
                'has_subscription' => true,
                'frequently_bought_together' => [
                    ['id' => 'ghee', 'name' => 'Desi Ghee', 'size' => '500 ml', 'price' => 9.99, 'image' => '/images/products/ghee.jpg'],
                    ['id' => 'toor-dal', 'name' => 'Organic Toor Dal', 'size' => '4 lb', 'price' => 7.99, 'image' => '/images/products/toor_dal.jpg'],
                ],
                'recipe_ingredients' => null,
            ],
            [
                'slug' => 'ghee',
                'name' => 'Desi Ghee',
                'subtitle_tag' => 'BILONA CHURNED COW BUTTER',
                'category' => 'dairy',
                'category_title' => 'Dairy & Ghee',
                'price' => 9.99,
                'original_price' => 9.99,
                'unit_price' => '$19.98 / L',
                'stock_badge' => 'In stock · best seller',
                'photo_label' => 'ghee jar',
                'image' => '/images/products/ghee.jpg',
                'size_main' => '500 ml',
                'size_sub' => '16.9 fl oz glass jar',
                'freshness_line' => 'Golden aromatic granular ghee with rich nutty flavor',
                'description' => 'Pure grass-fed clarified butter prepared using authentic slow-simmer methods for royal dishes.',
                'servings' => null,
                'cooking_time' => null,
                'is_recipe_kit' => false,
                'buy_again' => true,
                'has_subscription' => false,
                'frequently_bought_together' => [
                    ['id' => 'rice', 'name' => 'Basmati Rice', 'size' => '20 lb', 'price' => 24.99, 'image' => '/images/products/rice.jpg'],
                ],
                'recipe_ingredients' => null,
            ],
            [
                'slug' => 'biscuits',
                'name' => 'Glucose Biscuits',
                'subtitle_tag' => 'CLASSIC GOLDEN CHAI BISCUITS',
                'category' => 'snacks',
                'category_title' => 'Snacks & Chai',
                'price' => 3.49,
                'original_price' => 3.49,
                'unit_price' => '$4.36 / kg',
                'stock_badge' => 'In stock',
                'photo_label' => 'biscuits',
                'image' => '/images/products/biscuits.jpg',
                'size_main' => '800 g',
                'size_sub' => 'Family mega pack',
                'freshness_line' => 'Crispy crunchy golden wheat biscuits for morning & evening tea',
                'description' => 'The quintessential Indian tea-time biscuit loved across generations for dunking in piping hot chai.',
                'servings' => null,
                'cooking_time' => null,
                'is_recipe_kit' => false,
                'buy_again' => true,
                'has_subscription' => false,
                'frequently_bought_together' => [],
                'recipe_ingredients' => null,
            ],
            [
                'slug' => 'paneer',
                'name' => 'Malai Paneer',
                'subtitle_tag' => 'FRESH · MADE LOCALLY',
                'category' => 'dairy',
                'category_title' => 'Dairy & Paneer',
                'price' => 5.99,
                'original_price' => 5.99,
                'unit_price' => '$14.98 / kg',
                'stock_badge' => 'In stock · 24 left',
                'photo_label' => 'paneer block',
                'image' => '/images/products/paneer.jpg',
                'size_main' => '400 g',
                'size_sub' => '14.1 oz · 1 block',
                'freshness_line' => 'Pickup today from 4 pm · Best before Oct 2',
                'description' => 'Soft, full-cream paneer pressed in small batches. Holds its shape in tikka and melts into makhani.',
                'servings' => null,
                'cooking_time' => null,
                'is_recipe_kit' => false,
                'buy_again' => true,
                'has_subscription' => false,
                'frequently_bought_together' => [
                    ['id' => 'garam-masala', 'name' => 'Garam Masala', 'size' => '100 g', 'price' => 3.49, 'image' => '/images/products/garam_masala.jpg', 'checked' => true],
                    ['id' => 'garlic-naan', 'name' => 'Garlic Naan', 'size' => '4 pack', 'price' => 3.99, 'image' => '/images/products/sweets.jpg', 'checked' => false],
                    ['id' => 'kasuri-methi', 'name' => 'Kasuri Methi', 'size' => '50 g', 'price' => 2.49, 'image' => '/images/products/okra.jpg', 'checked' => false],
                ],
                'recipe_ingredients' => null,
            ],
            [
                'slug' => 'rice',
                'name' => 'Basmati Rice',
                'subtitle_tag' => 'AGED 2 YEARS · EXTRA LONG GRAIN',
                'category' => 'staples',
                'category_title' => 'Staples · Rice',
                'price' => 24.99,
                'original_price' => 24.99,
                'unit_price' => '$1.25 / lb',
                'stock_badge' => 'Staple · buy monthly',
                'photo_label' => 'rice sack',
                'image' => '/images/products/rice.jpg',
                'size_main' => '20 lb',
                'size_sub' => '9.07 kg · ~100 servings',
                'freshness_line' => 'Aged in climate-controlled storage for maximum aroma and non-sticky fluffiness.',
                'description' => 'Aged Himalayan long grain basmati rice. Slender grains elongate to twice their size when cooked.',
                'servings' => null,
                'cooking_time' => null,
                'is_recipe_kit' => false,
                'buy_again' => true,
                'has_subscription' => true,
                'frequently_bought_together' => [
                    ['id' => 'toor-dal', 'name' => 'Organic Toor Dal', 'size' => '4 lb', 'price' => 7.99, 'image' => '/images/products/toor_dal.jpg'],
                    ['id' => 'ghee', 'name' => 'Desi Ghee', 'size' => '500 ml', 'price' => 9.99, 'image' => '/images/products/ghee.jpg'],
                ],
                'recipe_ingredients' => null,
            ],

            // Recipe Kits
            [
                'slug' => 'veg-manchurian',
                'name' => 'Veg Manchurian Kit',
                'subtitle_tag' => 'INDO-CHINESE STREET STYLE',
                'category' => 'recipe-kits',
                'category_title' => 'Recipe Kits · Street Food',
                'price' => 16.49,
                'original_price' => 18.94,
                'unit_price' => '$4.12 / serving',
                'stock_badge' => '6 items',
                'photo_label' => 'manchurian',
                'image' => '/images/products/sweets.jpg',
                'size_main' => 'Kit for 4',
                'size_sub' => '6 fresh items included',
                'freshness_line' => 'Cabbage · Carrot · Spring onion · Corn starch · Soy sauce · Chilli sauce',
                'description' => 'Crispy fried vegetable dumplings tossed in a savoury, tangy, and spicy garlic-soy gravy. Complete with freshly chopped veggies and authentic sauces.',
                'servings' => 'Serves 4',
                'cooking_time' => '30 mins',
                'is_recipe_kit' => true,
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
                'recipe_ingredients' => [
                    'Fresh Shredded Cabbage & Carrot (500g)',
                    'Spring Onions & Green Chillies',
                    'Corn Starch & All-Purpose Flour Pack',
                    'Dark Soy Sauce & Chilli Garlic Sauce',
                ],
            ],
            [
                'slug' => 'paneer-curry',
                'name' => 'Paneer Butter Masala Kit',
                'subtitle_tag' => 'RESTAURANT STYLE GRAVY KIT',
                'category' => 'recipe-kits',
                'category_title' => 'Recipe Kits · Dinner',
                'price' => 19.99,
                'original_price' => 22.99,
                'unit_price' => '$5.00 / serving',
                'stock_badge' => 'Fresh kit · ready today',
                'photo_label' => 'butter masala',
                'image' => '/images/products/paneer_curry.jpg',
                'size_main' => 'Kit for 4',
                'size_sub' => 'All fresh & pantry ingredients included',
                'freshness_line' => 'Paneer · Tomato · Cream · Kasuri methi',
                'description' => 'Everything you need to make rich, silky restaurant-style Paneer Butter Masala in 25 minutes. Includes recipe card with step-by-step instructions.',
                'servings' => 'Serves 4',
                'cooking_time' => '25 mins',
                'is_recipe_kit' => true,
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
                'recipe_ingredients' => [
                    'Fresh Malai Paneer (400g)',
                    'Desi Butter & Cream Pack',
                    'Slow-cooked Makhani Gravy Base',
                    'Kasuri Methi & Whole Spices',
                ],
            ],
            [
                'slug' => 'biryani',
                'name' => 'Royal Dum Biryani Kit',
                'subtitle_tag' => 'HYDERABADI DUM SPECIAL',
                'category' => 'recipe-kits',
                'category_title' => 'Recipe Kits · Weekend Feast',
                'price' => 19.99,
                'original_price' => 22.99,
                'unit_price' => '$5.00 / serving',
                'stock_badge' => 'Chef recipe',
                'photo_label' => 'biryani kit',
                'image' => '/images/products/biryani.jpg',
                'size_main' => 'Feast for 4',
                'size_sub' => 'Includes royal saffron & kewra',
                'freshness_line' => 'Fragrant aged basmati paired with whole aromatics and barista fried onions',
                'description' => 'Layered aromatic Hyderabadi Dum Biryani kit. Contains 2-year aged long-grain basmati, authentic biryani masala pot, pure saffron strands, fried crispy onions, and desi ghee.',
                'servings' => 'Serves 4',
                'cooking_time' => '45 mins',
                'is_recipe_kit' => true,
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
                'recipe_ingredients' => [
                    'Royal Aged Basmati Rice (2 lb)',
                    'Shahi Biryani Pot Masala',
                    'Crispy Barista Fried Onions',
                    'Pure Saffron Strands & Cow Ghee',
                ],
            ],
            [
                'slug' => 'chana-masala',
                'name' => 'Punjabi Chana Masala Kit',
                'subtitle_tag' => 'AMRITSARI PIND RECIPE',
                'category' => 'recipe-kits',
                'category_title' => 'Recipe Kits · Classic Curry',
                'price' => 11.99,
                'original_price' => 13.99,
                'unit_price' => '$3.00 / serving',
                'stock_badge' => 'High protein',
                'photo_label' => 'chana kit',
                'image' => '/images/products/garam_masala.jpg',
                'size_main' => 'Kit for 4',
                'size_sub' => 'Rich dark tea-infused gravy',
                'freshness_line' => 'Organic kabuli chickpeas soaked & par-cooked with aromatic dry masala',
                'description' => 'Authentic Amritsari Chana Masala kit with roasted anardana (pomegranate seed), amchur, freshly ground garam masala, and ginger juliennes.',
                'servings' => 'Serves 4',
                'cooking_time' => '30 mins',
                'is_recipe_kit' => true,
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
                'recipe_ingredients' => [
                    'Kabuli Chickpeas (2 lb pre-soaked)',
                    'Amritsari Chana Masala Spice Blend',
                    'Anardana & Black Salt',
                    'Fresh Ginger & Green Chilli Pack',
                ],
            ],
            [
                'slug' => 'dal-tadka',
                'name' => 'Dal Tadka & Jeera Rice Kit',
                'subtitle_tag' => 'COMFORT FOOD ESSENTIAL',
                'category' => 'recipe-kits',
                'category_title' => 'Recipe Kits · Quick Dinners',
                'price' => 10.99,
                'original_price' => 12.49,
                'unit_price' => '$2.75 / serving',
                'stock_badge' => 'Ready in 20 mins',
                'photo_label' => 'dal kit',
                'image' => '/images/products/toor_dal.jpg',
                'size_main' => 'Kit for 4',
                'size_sub' => 'Double tadka aromatics',
                'freshness_line' => 'Yellow pigeon peas with cumin, mustard seeds, whole red chillies & garlic',
                'description' => 'Smoky dhaba-style yellow dal tadka paired with fragrant cumin jeera rice. Comes with pure desi ghee for the sizzle tempering.',
                'servings' => 'Serves 4',
                'cooking_time' => '20 mins',
                'is_recipe_kit' => true,
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
                'recipe_ingredients' => [
                    'Unpolished Toor Dal (1 lb)',
                    'Fragrant Jeera Rice (1 lb)',
                    'Tempering Spice Box (Jeera, Rai, Hing)',
                    'Cow Ghee & Dried Whole Red Chillies',
                ],
            ],

            // Additional catalog products
            [
                'slug' => 'sweets-box',
                'name' => 'Diwali Sweets Box',
                'subtitle_tag' => 'FESTIVAL PRE-ORDER · READY OCT 30',
                'category' => 'sweets',
                'category_title' => 'Festival Sweets & Mithai',
                'price' => 24.99,
                'original_price' => 29.99,
                'unit_price' => '$20.82 / kg',
                'stock_badge' => 'Pre-order · closes Oct 30',
                'photo_label' => 'mithai box',
                'image' => '/images/products/sweets.jpg',
                'size_main' => '1.2 kg',
                'size_sub' => 'Assorted 24 pcs luxury box',
                'freshness_line' => 'Handcrafted by master halwais with pure silver vark and organic pistachios',
                'description' => 'Deluxe festival presentation box featuring Kaju Katli, Pista Barfi, Motichoor Ladoo, and Besan Peda.',
                'servings' => null,
                'cooking_time' => null,
                'is_recipe_kit' => false,
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
                'recipe_ingredients' => null,
            ],
            [
                'slug' => 'garam-masala',
                'name' => 'Aromatic Garam Masala',
                'subtitle_tag' => 'WHOLE GROUND AROMATIC BLEND',
                'category' => 'spices',
                'category_title' => 'Spices & Seasoning',
                'price' => 3.49,
                'original_price' => 3.49,
                'unit_price' => '$34.90 / kg',
                'stock_badge' => 'In stock',
                'photo_label' => 'spice jar',
                'image' => '/images/products/garam_masala.jpg',
                'size_main' => '100 g',
                'size_sub' => '3.5 oz glass jar',
                'freshness_line' => 'Freshly stone-ground batches sealing in natural essential oils',
                'description' => 'Fragrant small-batch blend of green cardamom, cloves, cinnamon, mace, and black pepper.',
                'servings' => null,
                'cooking_time' => null,
                'is_recipe_kit' => false,
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
                'recipe_ingredients' => null,
            ],
            [
                'slug' => 'toor-dal',
                'name' => 'Organic Toor Dal',
                'subtitle_tag' => 'UNPOLISHED YELLOW PIGEON PEAS',
                'category' => 'staples',
                'category_title' => 'Staples · Pulses',
                'price' => 7.99,
                'original_price' => 7.99,
                'unit_price' => '$2.00 / lb',
                'stock_badge' => 'High protein',
                'photo_label' => 'dal bag',
                'image' => '/images/products/toor_dal.jpg',
                'size_main' => '4 lb',
                'size_sub' => '1.81 kg',
                'freshness_line' => 'Zero oil polish, naturally sun-dried pulses rich in dietary fiber',
                'description' => 'Premium unpolished toor dal for smooth, creamy dal tadka, rasam, and South Indian sambar.',
                'servings' => null,
                'cooking_time' => null,
                'is_recipe_kit' => false,
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
                'recipe_ingredients' => null,
            ],
            [
                'slug' => 'okra',
                'name' => 'Fresh Okra (Bhindi)',
                'subtitle_tag' => 'FARM FRESH · CRISP & TENDER',
                'category' => 'produce',
                'category_title' => 'Fresh Vegetables',
                'price' => 4.99,
                'original_price' => 4.99,
                'unit_price' => '$4.99 / lb',
                'stock_badge' => 'Harvested yesterday',
                'photo_label' => 'fresh okra',
                'image' => '/images/products/okra.jpg',
                'size_main' => '1 lb',
                'size_sub' => '~450 g',
                'freshness_line' => 'Hand-snapped tender green pods, guaranteed non-slimy when cooked',
                'description' => 'Crisp, tender baby okra ideal for crispy kurkuri bhindi, bharwan bhindi, or homestyle sabzi.',
                'servings' => null,
                'cooking_time' => null,
                'is_recipe_kit' => false,
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
                'recipe_ingredients' => null,
            ],
            [
                'slug' => 'curry-leaves',
                'name' => 'Fresh Curry Leaves (Kadi Patta)',
                'subtitle_tag' => 'INTENSELY AROMATIC HERB',
                'category' => 'produce',
                'category_title' => 'Fresh Herbs',
                'price' => 1.99,
                'original_price' => 1.99,
                'unit_price' => '$1.99 / bunch',
                'stock_badge' => 'Daily delivery',
                'photo_label' => 'curry leaves',
                'image' => '/images/products/curry_leaves.jpg',
                'size_main' => '1 fresh bunch',
                'size_sub' => 'Approx 30-40 leaves',
                'freshness_line' => 'Washed and chilled stems bursting with citrusy peppery oils',
                'description' => 'Essential tempering herb for South Indian and coastal curries, poha, upma, and dal tadka.',
                'servings' => null,
                'cooking_time' => null,
                'is_recipe_kit' => false,
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
                'recipe_ingredients' => null,
            ],
        ];

        foreach ($products as $item) {
            Product::create($item);
        }
    }
}
