<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Product::truncate();
        Schema::enableForeignKeyConstraints();

        $products = [
            // Staples & Buy It Again
            [
                'slug' => 'atta',
                'name' => 'Chakki Atta',
                'subtitle_tag' => '100% STONE GROUND WHOLE WHEAT',
                'category' => 'staples',
                'category_title' => 'Staples · Flour',
                'price' => 18.99,
                'original_price' => 18.99,
                'unit_price' => '$0.95 / lb',
                'stock_badge' => 'Staple · buy monthly',
                'photo_label' => 'atta bag',
                'image' => '/images/products/atta.jpg',
                'size_main' => '20 lb',
                'size_sub' => '9.07 kg · ~80 rotis',
                'freshness_line' => 'Freshly milled batch · Zero maida added',
                'description' => 'Traditional chakki stone-ground whole wheat flour for ultra-soft, fluffy phulkas and rotis.',
                'buy_again' => true,
                'has_subscription' => true,
                'frequently_bought_together' => [
                    ['id' => 'ghee', 'name' => 'Desi Ghee', 'size' => '500 ml', 'price' => 9.99, 'image' => '/images/products/ghee.jpg'],
                    ['id' => 'toor-dal', 'name' => 'Organic Toor Dal', 'size' => '4 lb', 'price' => 7.99, 'image' => '/images/products/toor_dal.jpg'],
                ],
            ],
            [
                'slug' => 'ghee',
                'name' => 'Desi Ghee',
                'subtitle_tag' => 'BILONA CHURNED COW BUTTER',
                'category' => 'dairy',
                'category_title' => 'Dairy & Ghee',
                'price' => 9.99,
                'original_price' => 9.99,
                'unit_price' => '$19.98 / L',
                'stock_badge' => 'In stock · best seller',
                'photo_label' => 'ghee jar',
                'image' => '/images/products/ghee.jpg',
                'size_main' => '500 ml',
                'size_sub' => '16.9 fl oz glass jar',
                'freshness_line' => 'Golden aromatic granular ghee with rich nutty flavor',
                'description' => 'Pure grass-fed clarified butter prepared using authentic slow-simmer methods for royal dishes.',
                'buy_again' => true,
                'has_subscription' => false,
                'frequently_bought_together' => [
                    ['id' => 'rice', 'name' => 'Basmati Rice', 'size' => '20 lb', 'price' => 24.99, 'image' => '/images/products/rice.jpg'],
                ],
            ],
            [
                'slug' => 'biscuits',
                'name' => 'Glucose Biscuits',
                'subtitle_tag' => 'CLASSIC GOLDEN CHAI BISCUITS',
                'category' => 'snacks',
                'category_title' => 'Snacks & Chai',
                'price' => 3.49,
                'original_price' => 3.49,
                'unit_price' => '$4.36 / kg',
                'stock_badge' => 'In stock',
                'photo_label' => 'biscuits',
                'image' => '/images/products/biscuits.jpg',
                'size_main' => '800 g',
                'size_sub' => 'Family mega pack',
                'freshness_line' => 'Crispy crunchy golden wheat biscuits for morning & evening tea',
                'description' => 'The quintessential Indian tea-time biscuit loved across generations for dunking in piping hot chai.',
                'buy_again' => true,
                'has_subscription' => false,
                'frequently_bought_together' => [],
            ],
            [
                'slug' => 'paneer',
                'name' => 'Malai Paneer',
                'subtitle_tag' => 'FRESH · MADE LOCALLY',
                'category' => 'dairy',
                'category_title' => 'Dairy & Paneer',
                'price' => 5.99,
                'original_price' => 5.99,
                'unit_price' => '$14.98 / kg',
                'stock_badge' => 'In stock · 24 left',
                'photo_label' => 'paneer block',
                'image' => '/images/products/paneer.jpg',
                'size_main' => '400 g',
                'size_sub' => '14.1 oz · 1 block',
                'freshness_line' => 'Pickup today from 4 pm · Best before Oct 2',
                'description' => 'Soft, full-cream paneer pressed in small batches. Holds its shape in tikka and melts into makhani.',
                'buy_again' => true,
                'has_subscription' => false,
                'frequently_bought_together' => [
                    ['id' => 'garam-masala', 'name' => 'Garam Masala', 'size' => '100 g', 'price' => 3.49, 'image' => '/images/products/garam_masala.jpg', 'checked' => true],
                    ['id' => 'garlic-naan', 'name' => 'Garlic Naan', 'size' => '4 pack', 'price' => 3.99, 'image' => '/images/products/sweets.jpg', 'checked' => false],
                    ['id' => 'kasuri-methi', 'name' => 'Kasuri Methi', 'size' => '50 g', 'price' => 2.49, 'image' => '/images/products/okra.jpg', 'checked' => false],
                ],
            ],
            [
                'slug' => 'rice',
                'name' => 'Basmati Rice',
                'subtitle_tag' => 'AGED 2 YEARS · EXTRA LONG GRAIN',
                'category' => 'staples',
                'category_title' => 'Staples · Rice',
                'price' => 24.99,
                'original_price' => 24.99,
                'unit_price' => '$1.25 / lb',
                'stock_badge' => 'Staple · buy monthly',
                'photo_label' => 'rice sack',
                'image' => '/images/products/rice.jpg',
                'size_main' => '20 lb',
                'size_sub' => '9.07 kg · ~100 servings',
                'freshness_line' => 'Aged in climate-controlled storage for maximum aroma and non-sticky fluffiness.',
                'description' => 'Aged Himalayan long grain basmati rice. Slender grains elongate to twice their size when cooked.',
                'buy_again' => true,
                'has_subscription' => true,
                'frequently_bought_together' => [
                    ['id' => 'ghee', 'name' => 'Desi Ghee', 'size' => '500 ml', 'price' => 9.99, 'image' => '/images/products/ghee.jpg'],
                ],
            ],
            [
                'slug' => 'sweets-box',
                'name' => 'Diwali Sweets Box',
                'subtitle_tag' => 'FESTIVAL PRE-ORDER · READY OCT 30',
                'category' => 'sweets',
                'category_title' => 'Festival Sweets & Mithai',
                'price' => 24.99,
                'original_price' => 29.99,
                'unit_price' => '$20.82 / kg',
                'stock_badge' => 'Pre-order · closes Oct 30',
                'photo_label' => 'mithai box',
                'image' => '/images/products/sweets.jpg',
                'size_main' => '1.2 kg',
                'size_sub' => 'Assorted 24 pcs luxury box',
                'freshness_line' => 'Handcrafted by master halwais with pure silver vark and organic pistachios',
                'description' => 'Deluxe festival presentation box featuring Kaju Katli, Pista Barfi, Motichoor Ladoo, and Besan Peda.',
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
            ],
            [
                'slug' => 'garam-masala',
                'name' => 'Aromatic Garam Masala',
                'subtitle_tag' => 'WHOLE GROUND AROMATIC BLEND',
                'category' => 'spices',
                'category_title' => 'Spices & Seasoning',
                'price' => 3.49,
                'original_price' => 3.49,
                'unit_price' => '$34.90 / kg',
                'stock_badge' => 'In stock',
                'photo_label' => 'spice jar',
                'image' => '/images/products/garam_masala.jpg',
                'size_main' => '100 g',
                'size_sub' => '3.5 oz glass jar',
                'freshness_line' => 'Freshly stone-ground batches sealing in natural essential oils',
                'description' => 'Fragrant small-batch blend of green cardamom, cloves, cinnamon, mace, and black pepper.',
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
            ],
            [
                'slug' => 'toor-dal',
                'name' => 'Organic Toor Dal',
                'subtitle_tag' => 'UNPOLISHED YELLOW PIGEON PEAS',
                'category' => 'staples',
                'category_title' => 'Staples · Pulses',
                'price' => 7.99,
                'original_price' => 7.99,
                'unit_price' => '$2.00 / lb',
                'stock_badge' => 'High protein',
                'photo_label' => 'dal bag',
                'image' => '/images/products/toor_dal.jpg',
                'size_main' => '4 lb',
                'size_sub' => '1.81 kg',
                'freshness_line' => 'Zero oil polish, naturally sun-dried pulses rich in dietary fiber',
                'description' => 'Premium unpolished toor dal for smooth, creamy dal tadka, rasam, and South Indian sambar.',
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
            ],
            [
                'slug' => 'okra',
                'name' => 'Fresh Okra (Bhindi)',
                'subtitle_tag' => 'FARM FRESH · CRISP & TENDER',
                'category' => 'produce',
                'category_title' => 'Fresh Vegetables',
                'price' => 4.99,
                'original_price' => 4.99,
                'unit_price' => '$4.99 / lb',
                'stock_badge' => 'Harvested yesterday',
                'photo_label' => 'fresh okra',
                'image' => '/images/products/okra.jpg',
                'size_main' => '1 lb',
                'size_sub' => '~450 g',
                'freshness_line' => 'Hand-snapped tender green pods, guaranteed non-slimy when cooked',
                'description' => 'Crisp, tender baby okra ideal for crispy kurkuri bhindi, bharwan bhindi, or homestyle sabzi.',
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
            ],
            [
                'slug' => 'curry-leaves',
                'name' => 'Fresh Curry Leaves (Kadi Patta)',
                'subtitle_tag' => 'INTENSELY AROMATIC HERB',
                'category' => 'produce',
                'category_title' => 'Fresh Herbs',
                'price' => 1.99,
                'original_price' => 1.99,
                'unit_price' => '$1.99 / bunch',
                'stock_badge' => 'Daily delivery',
                'photo_label' => 'curry leaves',
                'image' => '/images/products/curry_leaves.jpg',
                'size_main' => '1 fresh bunch',
                'size_sub' => 'Approx 30-40 leaves',
                'freshness_line' => 'Washed and chilled stems bursting with citrusy peppery oils',
                'description' => 'Essential tempering herb for South Indian and coastal curries, poha, upma, and dal tadka.',
                'buy_again' => false,
                'has_subscription' => false,
                'frequently_bought_together' => [],
            ],
        ];

        foreach ($products as $item) {
            Product::create($item);
        }
    }
}
